.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. counosh_qt test_counosh_qt
clean: FORCE
	$(MAKE) -C .. counosh_qt_clean test_counosh_qt_clean
check: FORCE
	$(MAKE) -C .. test_counosh_qt_check
counosh-qt counosh-qt.exe: FORCE
	 $(MAKE) -C .. counosh_qt
